### ISSUE TITLE
Occasional 503 status code errors returned to Mobile Commons

### ISSUE THREAD

**Issue by jonuy** [DoSomething/Uatu#16]
A few mData queries have returned a 503.

The response from the server looks like:

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<h1>Error 503 backend read error</h1>
<p>backend read error</p>
<h3>Guru Mediation:</h3>
<p>Details: cache-iad2137-IAD 1446761851 2450397113</p>
<hr>
<p>Varnish cache server</p>
```

One example of this happening is: https://secure.mcommons.com/mdatas/12368/mdata_queries/305200797

**Comment by sbsmith86** [comment]
@uy I'm going to set up tests in  runscope to help with monitoring. Also New Relic is set up here: https://rpm.newrelic.com/accounts/108038/applications/16901893

**Comment by sbsmith86** [comment]
We are set up on runscope so I am going to close this issue now.
